### ISSUE TITLE
No submenu for tools

### ISSUE THREAD

**Issue by antrrax** [DamirPorobic/kImageAnnotator#68]
The new version of Ksnip 1.6's is not displaying the submenu for the tools:
Marker, Arrow and Rectangle

I tested the Appimage version on linux mint 19.3 cinnamon x64
and the zip version on Windows 7 x64

**Comment by DamirPorobic** [comment]
Hey Leonardo, this might be because of #66.

You have to hold the click in order get the menu and select other items. Single click only selects the default tool. The little triangles indicate that there is an available menu: 
 
![image](https://user-images.githubusercontent.com/12796236/71955314-3b94c280-31e8-11ea-8868-afd2033c3537.png)

**Comment by DamirPorobic** [comment]
If you have any further questions, let me know.
